buildImage = 'mcr.microsoft.com/playwright:v1.51.1'
providers = []

[variables]
PATHNAME = '/railway-example'

[phases.install]
cmds = ['npm i']
onlyIncludeFiles = ['package.json']

[start]
cmd = 'npm start'
